# Prometheus configuration for Beverly Knits AI Supply Chain Planner
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Main application metrics
  - job_name: 'beverly-knits-app'
    static_configs:
      - targets: ['app:8000']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # ML inference service metrics
  - job_name: 'beverly-knits-ml'
    static_configs:
      - targets: ['ml-inference:8000']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:8080']
    metrics_path: /nginx_status
    scrape_interval: 30s

  # Node exporter (if available)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Docker metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

# Custom ML model performance metrics
  - job_name: 'ml-model-performance'
    static_configs:
      - targets: ['ml-inference:8000']
    metrics_path: /api/v1/metrics/models
    scrape_interval: 60s
    scrape_timeout: 30s

# Supply chain specific metrics
  - job_name: 'supply-chain-metrics'
    static_configs:
      - targets: ['app:8000']
    metrics_path: /api/v1/metrics/supply-chain
    scrape_interval: 60s
    scrape_timeout: 30s